export const ADD_TRAVEL_ACTIONS = {
    ADD_NEW_TRAVEL:'ADD_NEW_TRAVEL',
    CLOSE_NEW_TRAVEL:'CLOSE_NEW_TRAVEL',
    ADD_PROJECT_DETAILS:'ADD_PROJECT_DETAILS',
    ADD_EXPENSE_DETAILS:'ADD_EXPENSE_DETAILS'
};
